colorScheme = "slate"
defaultAppearance = "light" # valid options: light or dark
autoSwitchAppearance = true

enableSearch = true
enableCodeCopy = true
enableImageLazyLoading = true
enableImageWebp = true
enableQuicklink = true

fingerprintAlgorithm = "sha256"

# Which content section(s) count as "articles" for the homepage recent list
mainSections = ["animals"]

description = "A Girl Scout Silver Award project about Emotional Support Animals, Service Animals, and Therapy Animals."

[header]
  layout = "basic" # valid options: basic, hamburger, hybrid, custom
  showTitle = true

[footer]
  showCopyright = true
  showThemeAttribution = true
  showAppearanceSwitcher = true
  showScrollToTop = true

[homepage]
  layout = "page" # valid options: page, profile, custom
  showRecent = true
  recentLimit = 6

[article]
  showDate = false
  showAuthor = false
  showBreadcrumbs = false
  showDraftLabel = true
  showEdit = false
  showHeadingAnchors = true
  showPagination = true
  showReadingTime = false
  showTableOfContents = true
  showTaxonomies = false
  showWordCount = false
  showComments = false

[list]
  showBreadcrumbs = false
  showSummary = true
  showTableOfContents = false
  showTaxonomies = false

[sitemap]
  excludedKinds = ["taxonomy", "term"]
